Sharing feature
mbta/screenplay pull request #217
Opened 2023-06-02 19:31 UTC by PaulJKim

**Asana task**: [[Screenplay] Implement sharing feature](https://app.asana.com/0/1185117109217432/1204083894737784/f)

Description
This PR adds some new buttons and a dropdown that encompass a new action bar for screen details within a place row. Along with these, there are also some added tooltips and a toast that appears when the link is copied to the user's clipboard. Designs are linked in the Asana Task.

2023-06-12 12:09 UTC, hannahpurcell requested changes
Couple of visual deviations, before I get into the nitty gritty code review: 

The tooltips should be centered on the icon, but are left-aligned:
![Screenshot 2023-06-12 at 8 03 49 AM](https://github.com/mbta/screenplay/assets/69368883/c43029dd-46c4-49f9-af33-fa61ee79ef8e)

The logic by which the buttons collapse into the "More" icon seems buggy. Attaching an instance where it should have collapsed but wrapped instead, and another instance where it collapsed, but also seems that it should have had room to not collapse? Or maybe we always want to collapse them for the countdown clocks?

![Screenshot 2023-06-12 at 8 01 04 AM](https://github.com/mbta/screenplay/assets/69368883/5c133b83-033f-4ced-ade1-27f9f4c4f268)

![Screenshot 2023-06-12 at 8 03 20 AM](https://github.com/mbta/screenplay/assets/69368883/7e35ec24-1280-466e-9d01-13b0efe0a643)

2023-06-12 12:58 UTC, hannahpurcell commented
Ohhhhh I see I see. I interpreted the "more" button to be a collapse situation, but it doesn't need to be. It can be specific to screen type / number of screens. Works for me

2023-06-12 12:58 UTC, hannahpurcell commented
Ohhhhh I see I see. I interpreted the "more" button to be a collapse situation, but it doesn't need to be. It can be specific to screen type / number of screens. Works for me

2023-06-12 14:35 UTC, hannahpurcell reviewed
Ok great! Two cosmetic edits, and then the one visual tweak I already mentioned.

Plus, the toast needs some styling updates. To name a few (not comprehensive list):
- SVG checkmark should be 24px, not 18px
- Margin between svg and text should be bigger, I think
- Shouldn't have a dark border
- Should have a darker, thicker shadow

![Screenshot 2023-06-12 at 10 31 39 AM](https://github.com/mbta/screenplay/assets/69368883/636537f3-6288-437b-8dbd-1abebb498eee)

[Figma](https://www.figma.com/file/w40fdAbU6EgnydfOLtBXxI/MorePolished_AccessWebScreens?type=design&node-id=4961-45405&t=cipgbddRthpXjT55-4):
![Screenshot 2023-06-12 at 10 30 42 AM](https://github.com/mbta/screenplay/assets/69368883/18f8239d-dfc8-4723-b247-a4b142f3d9c0)

2023-06-13 18:25 UTC, PaulJKim commented
Hmm interesting, I'm not able to replicate the misaligned tooltip 🤔 
![Screenshot 2023-06-13 at 2 24 52 PM](https://github.com/mbta/screenplay/assets/16074540/2180f8b4-7ab6-44b8-9b4c-9fecaab8a3ca)

2023-06-13 18:55 UTC, PaulJKim commented on assets/js/components/Dashboard/ScreenDetailActionBar.tsx
> +  isMultipleScreens?: boolean;
Oh yes agreed. I think that's much simpler!

2023-06-22 15:27 UTC, hannahpurcell commented
Hmmmph.... I did reproduce the uncentered tooltip again, in both Chrome and Firefox. If you try to reproduce it once more and still cannot, I'd say either phone a friend, or we can merge it and look at it in dev

2023-06-23 17:22 UTC, merged